version: '3.4'

services:
  debt:
    image: ${DOCKER_REGISTRY-}debt
    build:
      context: .
      dockerfile: Debt/Debt.Api/Dockerfile
    ports:
      - "127.0.0.1:10001:80"
  access_control:
    image: ${DOCKER_REGISTRY-}access_control
    container_name: access_control
    build:
      context: .
      dockerfile: AccessControl/AccessControl.Api/Dockerfile
    ports:
      - "127.0.0.1:10002:80"
  debt_db:
    image: postgres
    container_name: debt_db
    user: postgres
    restart: always
    volumes:
      - debt_db_data:/var/lib/postgresal/data
    environment:
      - POSTGRES_DB=debt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    expose:
      - "127.0.0.1:8001:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  access_control_db:
    image: postgres
    container_name: access_control_db
    user: postgres
    restart: always
    volumes:
      - access_control_db_data:/var/lib/postgresal/data
    environment:
      - POSTGRES_DB=access_control
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    expose:
      - "127.0.0.1:8002:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  debt_db_data:    
  access_control_db_data: