# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Unit Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x', '8.0.x']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Display dotnet version
      run: dotnet --version
      
    - name: Debt Restore dependencies 
      run: dotnet restore ./Debt/Debt.Tests
      
    - name: Debt Build
      run: dotnet build ./Debt/Debt.Tests --no-restore
      
    - name: Debt Test
      run: dotnet test ./Debt/Debt.Tests --no-build --verbosity normal

    - name: AccessControl Restore dependencies 
      run: dotnet restore ./AccessControl/AccessControl.Tests
      
    - name: AccessControl Build
      run: dotnet build ./AccessControl/AccessControl.Tests --no-restore
      
    - name: AccessControl Test
      run: dotnet test ./AccessControl/AccessControl.Tests --no-build --verbosity normal